module.exports = Object.freeze({
  PLAYER_RADIUS: 20,
  PLAYER_MAX_HP: 100,
  PLAYER_SPEED: 100,
  PLAYER_FIRE_COOLDOWN: 0.5,
  PLAYER_HP_RECOVERY_RATE: 1,

  BULLET_RADIUS: 15,
  BULLET_SPEED: 150,
  BULLET_DAMAGE: 10,
  COLLISION_DAMAGE: 50,
  PLAYER_COLLISION_COOLDOWN: 0.5,

  SCORE_BULLET_HIT: 10,
  SCORE_KILL: 100,
  SCORE_PER_SECOND: 0.5,

  SMAP_SIZE: 100,
  CLIENT_UPDATE_PER_SECOND: 60,
  SERVER_UPDATE_PER_SECOND: 40,

  MAGIC_WORD: '#f0rever',

  NUM_BOTS: 100,
  MAP_SIZE: 6000,
  MAP_GRID_SIZE: 100,
  MAP_OBJ_GRID_SIZE: 50,
  MSG_TYPES: {
    JOIN_GAME: 'join_game',
    GAME_UPDATE: 'update',
    UPDATE_CANVAS_SIZE: 'update_canvas_size',
    INPUT_MOVEDIRECTION: 'input_movedir',
    INPUT_FIRE: 'input_fire',
    INPUT_FIREDIRECTION: 'input_firedir',
    INPUT_TOGGLE: 'input_toggle',
    GAME_OVER: 'dead',
  },
});
